# Generated by Django 4.0.3 on 2022-04-07 18:16

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageResizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, max_length=100, null=True)),
                ('longitude', models.FloatField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('image', stdimage.models.StdImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'image_resizer',
            },
        ),
    ]
