# Generated by Django 4.0.3 on 2022-04-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_resizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageresizer',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imageresizer',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
